//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 12.09.2017 13:16:28
namespace ODataClientConsoleApplication.DataAccess.DataBase
{
    /// <summary>
    /// There are no comments for CurrencyRateByTimeSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("CurrencyRateByTimeSingle")]
    public partial class CurrencyRateByTimeSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<CurrencyRateByTime>
    {
        /// <summary>
        /// Initialize a new CurrencyRateByTimeSingle object.
        /// </summary>
        public CurrencyRateByTimeSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new CurrencyRateByTimeSingle object.
        /// </summary>
        public CurrencyRateByTimeSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new CurrencyRateByTimeSingle object.
        /// </summary>
        public CurrencyRateByTimeSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<CurrencyRateByTime> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for BankDepartment in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("BankDepartment")]
        public global::ODataClientConsoleApplication.DataAccess.DataBase.BankDepartmentSingle BankDepartment
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._BankDepartment == null))
                {
                    this._BankDepartment = new global::ODataClientConsoleApplication.DataAccess.DataBase.BankDepartmentSingle(this.Context, GetPath("BankDepartment"));
                }
                return this._BankDepartment;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::ODataClientConsoleApplication.DataAccess.DataBase.BankDepartmentSingle _BankDepartment;
        /// <summary>
        /// There are no comments for Currency in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Currency")]
        public global::ODataClientConsoleApplication.DataAccess.DataBase.CurrencySingle Currency
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Currency == null))
                {
                    this._Currency = new global::ODataClientConsoleApplication.DataAccess.DataBase.CurrencySingle(this.Context, GetPath("Currency"));
                }
                return this._Currency;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::ODataClientConsoleApplication.DataAccess.DataBase.CurrencySingle _Currency;
    }
    /// <summary>
    /// There are no comments for CurrencyRateByTime in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("CurrencyRateByTime")]
    public partial class CurrencyRateByTime : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new CurrencyRateByTime object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="dateTime">Initial value of DateTime.</param>
        /// <param name="sale">Initial value of Sale.</param>
        /// <param name="purchase">Initial value of Purchase.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static CurrencyRateByTime CreateCurrencyRateByTime(int ID, global::System.DateTimeOffset dateTime, double sale, double purchase)
        {
            CurrencyRateByTime currencyRateByTime = new CurrencyRateByTime();
            currencyRateByTime.Id = ID;
            currencyRateByTime.DateTime = dateTime;
            currencyRateByTime.Sale = sale;
            currencyRateByTime.Purchase = purchase;
            return currencyRateByTime;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property CurrencyId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CurrencyId")]
        public global::System.Nullable<int> CurrencyId
        {
            get
            {
                return this._CurrencyId;
            }
            set
            {
                this.OnCurrencyIdChanging(value);
                this._CurrencyId = value;
                this.OnCurrencyIdChanged();
                this.OnPropertyChanged("CurrencyId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<int> _CurrencyId;
        partial void OnCurrencyIdChanging(global::System.Nullable<int> value);
        partial void OnCurrencyIdChanged();
        /// <summary>
        /// There are no comments for Property BankDepartmentId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("BankDepartmentId")]
        public global::System.Nullable<int> BankDepartmentId
        {
            get
            {
                return this._BankDepartmentId;
            }
            set
            {
                this.OnBankDepartmentIdChanging(value);
                this._BankDepartmentId = value;
                this.OnBankDepartmentIdChanged();
                this.OnPropertyChanged("BankDepartmentId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<int> _BankDepartmentId;
        partial void OnBankDepartmentIdChanging(global::System.Nullable<int> value);
        partial void OnBankDepartmentIdChanged();
        /// <summary>
        /// There are no comments for Property DateTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("DateTime")]
        public global::System.DateTimeOffset DateTime
        {
            get
            {
                return this._DateTime;
            }
            set
            {
                this.OnDateTimeChanging(value);
                this._DateTime = value;
                this.OnDateTimeChanged();
                this.OnPropertyChanged("DateTime");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.DateTimeOffset _DateTime;
        partial void OnDateTimeChanging(global::System.DateTimeOffset value);
        partial void OnDateTimeChanged();
        /// <summary>
        /// There are no comments for Property Sale in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Sale")]
        public double Sale
        {
            get
            {
                return this._Sale;
            }
            set
            {
                this.OnSaleChanging(value);
                this._Sale = value;
                this.OnSaleChanged();
                this.OnPropertyChanged("Sale");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private double _Sale;
        partial void OnSaleChanging(double value);
        partial void OnSaleChanged();
        /// <summary>
        /// There are no comments for Property Purchase in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Purchase")]
        public double Purchase
        {
            get
            {
                return this._Purchase;
            }
            set
            {
                this.OnPurchaseChanging(value);
                this._Purchase = value;
                this.OnPurchaseChanged();
                this.OnPropertyChanged("Purchase");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private double _Purchase;
        partial void OnPurchaseChanging(double value);
        partial void OnPurchaseChanged();
        /// <summary>
        /// There are no comments for Property BankDepartment in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("BankDepartment")]
        public global::ODataClientConsoleApplication.DataAccess.DataBase.BankDepartment BankDepartment
        {
            get
            {
                return this._BankDepartment;
            }
            set
            {
                this.OnBankDepartmentChanging(value);
                this._BankDepartment = value;
                this.OnBankDepartmentChanged();
                this.OnPropertyChanged("BankDepartment");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::ODataClientConsoleApplication.DataAccess.DataBase.BankDepartment _BankDepartment;
        partial void OnBankDepartmentChanging(global::ODataClientConsoleApplication.DataAccess.DataBase.BankDepartment value);
        partial void OnBankDepartmentChanged();
        /// <summary>
        /// There are no comments for Property Currency in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Currency")]
        public global::ODataClientConsoleApplication.DataAccess.DataBase.Currency Currency
        {
            get
            {
                return this._Currency;
            }
            set
            {
                this.OnCurrencyChanging(value);
                this._Currency = value;
                this.OnCurrencyChanged();
                this.OnPropertyChanged("Currency");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::ODataClientConsoleApplication.DataAccess.DataBase.Currency _Currency;
        partial void OnCurrencyChanging(global::ODataClientConsoleApplication.DataAccess.DataBase.Currency value);
        partial void OnCurrencyChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for BankDepartmentSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("BankDepartmentSingle")]
    public partial class BankDepartmentSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<BankDepartment>
    {
        /// <summary>
        /// Initialize a new BankDepartmentSingle object.
        /// </summary>
        public BankDepartmentSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new BankDepartmentSingle object.
        /// </summary>
        public BankDepartmentSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new BankDepartmentSingle object.
        /// </summary>
        public BankDepartmentSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<BankDepartment> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Bank in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Bank")]
        public global::ODataClientConsoleApplication.DataAccess.DataBase.BankSingle Bank
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Bank == null))
                {
                    this._Bank = new global::ODataClientConsoleApplication.DataAccess.DataBase.BankSingle(this.Context, GetPath("Bank"));
                }
                return this._Bank;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::ODataClientConsoleApplication.DataAccess.DataBase.BankSingle _Bank;
        /// <summary>
        /// There are no comments for City in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("City")]
        public global::ODataClientConsoleApplication.DataAccess.DataBase.CitySingle City
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._City == null))
                {
                    this._City = new global::ODataClientConsoleApplication.DataAccess.DataBase.CitySingle(this.Context, GetPath("City"));
                }
                return this._City;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::ODataClientConsoleApplication.DataAccess.DataBase.CitySingle _City;
        /// <summary>
        /// There are no comments for CurrencyRateByTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CurrencyRateByTime")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::ODataClientConsoleApplication.DataAccess.DataBase.CurrencyRateByTime> CurrencyRateByTime
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._CurrencyRateByTime == null))
                {
                    this._CurrencyRateByTime = Context.CreateQuery<global::ODataClientConsoleApplication.DataAccess.DataBase.CurrencyRateByTime>(GetPath("CurrencyRateByTime"));
                }
                return this._CurrencyRateByTime;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::ODataClientConsoleApplication.DataAccess.DataBase.CurrencyRateByTime> _CurrencyRateByTime;
    }
    /// <summary>
    /// There are no comments for BankDepartment in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("BankDepartment")]
    public partial class BankDepartment : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new BankDepartment object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static BankDepartment CreateBankDepartment(int ID)
        {
            BankDepartment bankDepartment = new BankDepartment();
            bankDepartment.Id = ID;
            return bankDepartment;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Address in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Address")]
        public string Address
        {
            get
            {
                return this._Address;
            }
            set
            {
                this.OnAddressChanging(value);
                this._Address = value;
                this.OnAddressChanged();
                this.OnPropertyChanged("Address");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Address;
        partial void OnAddressChanging(string value);
        partial void OnAddressChanged();
        /// <summary>
        /// There are no comments for Property CityId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CityId")]
        public global::System.Nullable<int> CityId
        {
            get
            {
                return this._CityId;
            }
            set
            {
                this.OnCityIdChanging(value);
                this._CityId = value;
                this.OnCityIdChanged();
                this.OnPropertyChanged("CityId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<int> _CityId;
        partial void OnCityIdChanging(global::System.Nullable<int> value);
        partial void OnCityIdChanged();
        /// <summary>
        /// There are no comments for Property BankId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("BankId")]
        public global::System.Nullable<int> BankId
        {
            get
            {
                return this._BankId;
            }
            set
            {
                this.OnBankIdChanging(value);
                this._BankId = value;
                this.OnBankIdChanged();
                this.OnPropertyChanged("BankId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<int> _BankId;
        partial void OnBankIdChanging(global::System.Nullable<int> value);
        partial void OnBankIdChanged();
        /// <summary>
        /// There are no comments for Property Bank in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Bank")]
        public global::ODataClientConsoleApplication.DataAccess.DataBase.Bank Bank
        {
            get
            {
                return this._Bank;
            }
            set
            {
                this.OnBankChanging(value);
                this._Bank = value;
                this.OnBankChanged();
                this.OnPropertyChanged("Bank");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::ODataClientConsoleApplication.DataAccess.DataBase.Bank _Bank;
        partial void OnBankChanging(global::ODataClientConsoleApplication.DataAccess.DataBase.Bank value);
        partial void OnBankChanged();
        /// <summary>
        /// There are no comments for Property City in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("City")]
        public global::ODataClientConsoleApplication.DataAccess.DataBase.City City
        {
            get
            {
                return this._City;
            }
            set
            {
                this.OnCityChanging(value);
                this._City = value;
                this.OnCityChanged();
                this.OnPropertyChanged("City");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::ODataClientConsoleApplication.DataAccess.DataBase.City _City;
        partial void OnCityChanging(global::ODataClientConsoleApplication.DataAccess.DataBase.City value);
        partial void OnCityChanged();
        /// <summary>
        /// There are no comments for Property CurrencyRateByTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CurrencyRateByTime")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::ODataClientConsoleApplication.DataAccess.DataBase.CurrencyRateByTime> CurrencyRateByTime
        {
            get
            {
                return this._CurrencyRateByTime;
            }
            set
            {
                this.OnCurrencyRateByTimeChanging(value);
                this._CurrencyRateByTime = value;
                this.OnCurrencyRateByTimeChanged();
                this.OnPropertyChanged("CurrencyRateByTime");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::ODataClientConsoleApplication.DataAccess.DataBase.CurrencyRateByTime> _CurrencyRateByTime = new global::Microsoft.OData.Client.DataServiceCollection<global::ODataClientConsoleApplication.DataAccess.DataBase.CurrencyRateByTime>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnCurrencyRateByTimeChanging(global::Microsoft.OData.Client.DataServiceCollection<global::ODataClientConsoleApplication.DataAccess.DataBase.CurrencyRateByTime> value);
        partial void OnCurrencyRateByTimeChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for CurrencySingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("CurrencySingle")]
    public partial class CurrencySingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Currency>
    {
        /// <summary>
        /// Initialize a new CurrencySingle object.
        /// </summary>
        public CurrencySingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new CurrencySingle object.
        /// </summary>
        public CurrencySingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new CurrencySingle object.
        /// </summary>
        public CurrencySingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Currency> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for CurrencyRateByTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CurrencyRateByTime")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::ODataClientConsoleApplication.DataAccess.DataBase.CurrencyRateByTime> CurrencyRateByTime
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._CurrencyRateByTime == null))
                {
                    this._CurrencyRateByTime = Context.CreateQuery<global::ODataClientConsoleApplication.DataAccess.DataBase.CurrencyRateByTime>(GetPath("CurrencyRateByTime"));
                }
                return this._CurrencyRateByTime;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::ODataClientConsoleApplication.DataAccess.DataBase.CurrencyRateByTime> _CurrencyRateByTime;
    }
    /// <summary>
    /// There are no comments for Currency in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Currency")]
    public partial class Currency : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Currency object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Currency CreateCurrency(int ID)
        {
            Currency currency = new Currency();
            currency.Id = ID;
            return currency;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property CurrencyRateByTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CurrencyRateByTime")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::ODataClientConsoleApplication.DataAccess.DataBase.CurrencyRateByTime> CurrencyRateByTime
        {
            get
            {
                return this._CurrencyRateByTime;
            }
            set
            {
                this.OnCurrencyRateByTimeChanging(value);
                this._CurrencyRateByTime = value;
                this.OnCurrencyRateByTimeChanged();
                this.OnPropertyChanged("CurrencyRateByTime");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::ODataClientConsoleApplication.DataAccess.DataBase.CurrencyRateByTime> _CurrencyRateByTime = new global::Microsoft.OData.Client.DataServiceCollection<global::ODataClientConsoleApplication.DataAccess.DataBase.CurrencyRateByTime>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnCurrencyRateByTimeChanging(global::Microsoft.OData.Client.DataServiceCollection<global::ODataClientConsoleApplication.DataAccess.DataBase.CurrencyRateByTime> value);
        partial void OnCurrencyRateByTimeChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for BankSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("BankSingle")]
    public partial class BankSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Bank>
    {
        /// <summary>
        /// Initialize a new BankSingle object.
        /// </summary>
        public BankSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new BankSingle object.
        /// </summary>
        public BankSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new BankSingle object.
        /// </summary>
        public BankSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Bank> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for BankDepartment in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("BankDepartment")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::ODataClientConsoleApplication.DataAccess.DataBase.BankDepartment> BankDepartment
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._BankDepartment == null))
                {
                    this._BankDepartment = Context.CreateQuery<global::ODataClientConsoleApplication.DataAccess.DataBase.BankDepartment>(GetPath("BankDepartment"));
                }
                return this._BankDepartment;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::ODataClientConsoleApplication.DataAccess.DataBase.BankDepartment> _BankDepartment;
    }
    /// <summary>
    /// There are no comments for Bank in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Bank")]
    public partial class Bank : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Bank object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Bank CreateBank(int ID)
        {
            Bank bank = new Bank();
            bank.Id = ID;
            return bank;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property BankDepartment in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("BankDepartment")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::ODataClientConsoleApplication.DataAccess.DataBase.BankDepartment> BankDepartment
        {
            get
            {
                return this._BankDepartment;
            }
            set
            {
                this.OnBankDepartmentChanging(value);
                this._BankDepartment = value;
                this.OnBankDepartmentChanged();
                this.OnPropertyChanged("BankDepartment");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::ODataClientConsoleApplication.DataAccess.DataBase.BankDepartment> _BankDepartment = new global::Microsoft.OData.Client.DataServiceCollection<global::ODataClientConsoleApplication.DataAccess.DataBase.BankDepartment>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnBankDepartmentChanging(global::Microsoft.OData.Client.DataServiceCollection<global::ODataClientConsoleApplication.DataAccess.DataBase.BankDepartment> value);
        partial void OnBankDepartmentChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for CitySingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("CitySingle")]
    public partial class CitySingle : global::Microsoft.OData.Client.DataServiceQuerySingle<City>
    {
        /// <summary>
        /// Initialize a new CitySingle object.
        /// </summary>
        public CitySingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new CitySingle object.
        /// </summary>
        public CitySingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new CitySingle object.
        /// </summary>
        public CitySingle(global::Microsoft.OData.Client.DataServiceQuerySingle<City> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for BankDepartment in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("BankDepartment")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::ODataClientConsoleApplication.DataAccess.DataBase.BankDepartment> BankDepartment
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._BankDepartment == null))
                {
                    this._BankDepartment = Context.CreateQuery<global::ODataClientConsoleApplication.DataAccess.DataBase.BankDepartment>(GetPath("BankDepartment"));
                }
                return this._BankDepartment;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::ODataClientConsoleApplication.DataAccess.DataBase.BankDepartment> _BankDepartment;
    }
    /// <summary>
    /// There are no comments for City in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("City")]
    public partial class City : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new City object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static City CreateCity(int ID)
        {
            City city = new City();
            city.Id = ID;
            return city;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property BankDepartment in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("BankDepartment")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::ODataClientConsoleApplication.DataAccess.DataBase.BankDepartment> BankDepartment
        {
            get
            {
                return this._BankDepartment;
            }
            set
            {
                this.OnBankDepartmentChanging(value);
                this._BankDepartment = value;
                this.OnBankDepartmentChanged();
                this.OnPropertyChanged("BankDepartment");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::ODataClientConsoleApplication.DataAccess.DataBase.BankDepartment> _BankDepartment = new global::Microsoft.OData.Client.DataServiceCollection<global::ODataClientConsoleApplication.DataAccess.DataBase.BankDepartment>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnBankDepartmentChanging(global::Microsoft.OData.Client.DataServiceCollection<global::ODataClientConsoleApplication.DataAccess.DataBase.BankDepartment> value);
        partial void OnBankDepartmentChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::ODataClientConsoleApplication.DataAccess.DataBase.CurrencyRateByTime as global::ODataClientConsoleApplication.DataAccess.DataBase.CurrencyRateByTimeSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::ODataClientConsoleApplication.DataAccess.DataBase.CurrencyRateByTimeSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ODataClientConsoleApplication.DataAccess.DataBase.CurrencyRateByTime> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::ODataClientConsoleApplication.DataAccess.DataBase.CurrencyRateByTimeSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::ODataClientConsoleApplication.DataAccess.DataBase.CurrencyRateByTime as global::ODataClientConsoleApplication.DataAccess.DataBase.CurrencyRateByTimeSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::ODataClientConsoleApplication.DataAccess.DataBase.CurrencyRateByTimeSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ODataClientConsoleApplication.DataAccess.DataBase.CurrencyRateByTime> source,
            int id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::ODataClientConsoleApplication.DataAccess.DataBase.CurrencyRateByTimeSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::ODataClientConsoleApplication.DataAccess.DataBase.BankDepartment as global::ODataClientConsoleApplication.DataAccess.DataBase.BankDepartmentSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::ODataClientConsoleApplication.DataAccess.DataBase.BankDepartmentSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ODataClientConsoleApplication.DataAccess.DataBase.BankDepartment> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::ODataClientConsoleApplication.DataAccess.DataBase.BankDepartmentSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::ODataClientConsoleApplication.DataAccess.DataBase.BankDepartment as global::ODataClientConsoleApplication.DataAccess.DataBase.BankDepartmentSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::ODataClientConsoleApplication.DataAccess.DataBase.BankDepartmentSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ODataClientConsoleApplication.DataAccess.DataBase.BankDepartment> source,
            int id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::ODataClientConsoleApplication.DataAccess.DataBase.BankDepartmentSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::ODataClientConsoleApplication.DataAccess.DataBase.Currency as global::ODataClientConsoleApplication.DataAccess.DataBase.CurrencySingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::ODataClientConsoleApplication.DataAccess.DataBase.CurrencySingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ODataClientConsoleApplication.DataAccess.DataBase.Currency> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::ODataClientConsoleApplication.DataAccess.DataBase.CurrencySingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::ODataClientConsoleApplication.DataAccess.DataBase.Currency as global::ODataClientConsoleApplication.DataAccess.DataBase.CurrencySingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::ODataClientConsoleApplication.DataAccess.DataBase.CurrencySingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ODataClientConsoleApplication.DataAccess.DataBase.Currency> source,
            int id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::ODataClientConsoleApplication.DataAccess.DataBase.CurrencySingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::ODataClientConsoleApplication.DataAccess.DataBase.Bank as global::ODataClientConsoleApplication.DataAccess.DataBase.BankSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::ODataClientConsoleApplication.DataAccess.DataBase.BankSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ODataClientConsoleApplication.DataAccess.DataBase.Bank> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::ODataClientConsoleApplication.DataAccess.DataBase.BankSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::ODataClientConsoleApplication.DataAccess.DataBase.Bank as global::ODataClientConsoleApplication.DataAccess.DataBase.BankSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::ODataClientConsoleApplication.DataAccess.DataBase.BankSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ODataClientConsoleApplication.DataAccess.DataBase.Bank> source,
            int id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::ODataClientConsoleApplication.DataAccess.DataBase.BankSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::ODataClientConsoleApplication.DataAccess.DataBase.City as global::ODataClientConsoleApplication.DataAccess.DataBase.CitySingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::ODataClientConsoleApplication.DataAccess.DataBase.CitySingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ODataClientConsoleApplication.DataAccess.DataBase.City> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::ODataClientConsoleApplication.DataAccess.DataBase.CitySingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::ODataClientConsoleApplication.DataAccess.DataBase.City as global::ODataClientConsoleApplication.DataAccess.DataBase.CitySingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::ODataClientConsoleApplication.DataAccess.DataBase.CitySingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ODataClientConsoleApplication.DataAccess.DataBase.City> source,
            int id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::ODataClientConsoleApplication.DataAccess.DataBase.CitySingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
    }
}
namespace ODataClientConsoleApplication.Default
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("Container")]
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "DataAccess.DataBase", "ODataClientConsoleApplication.DataAccess.DataBase");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Default", "ODataClientConsoleApplication.Default");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            global::Microsoft.OData.Client.OriginalNameAttribute originalNameAttribute = (global::Microsoft.OData.Client.OriginalNameAttribute)global::System.Linq.Enumerable.SingleOrDefault(global::Microsoft.OData.Client.Utility.GetCustomAttributes(clientType, typeof(global::Microsoft.OData.Client.OriginalNameAttribute), true));
            if (clientType.Namespace.Equals("ODataClientConsoleApplication.DataAccess.DataBase", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("DataAccess.DataBase.", originalNameAttribute.OriginalName);
                }
                return string.Concat("DataAccess.DataBase.", clientType.Name);
            }
            if (clientType.Namespace.Equals("ODataClientConsoleApplication.Default", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Default.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Default.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for CurrencyRateByTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CurrencyRateByTime")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::ODataClientConsoleApplication.DataAccess.DataBase.CurrencyRateByTime> CurrencyRateByTime
        {
            get
            {
                if ((this._CurrencyRateByTime == null))
                {
                    this._CurrencyRateByTime = base.CreateQuery<global::ODataClientConsoleApplication.DataAccess.DataBase.CurrencyRateByTime>("CurrencyRateByTime");
                }
                return this._CurrencyRateByTime;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::ODataClientConsoleApplication.DataAccess.DataBase.CurrencyRateByTime> _CurrencyRateByTime;
        /// <summary>
        /// There are no comments for BankDepartment in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("BankDepartment")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::ODataClientConsoleApplication.DataAccess.DataBase.BankDepartment> BankDepartment
        {
            get
            {
                if ((this._BankDepartment == null))
                {
                    this._BankDepartment = base.CreateQuery<global::ODataClientConsoleApplication.DataAccess.DataBase.BankDepartment>("BankDepartment");
                }
                return this._BankDepartment;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::ODataClientConsoleApplication.DataAccess.DataBase.BankDepartment> _BankDepartment;
        /// <summary>
        /// There are no comments for Currency in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Currency")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::ODataClientConsoleApplication.DataAccess.DataBase.Currency> Currency
        {
            get
            {
                if ((this._Currency == null))
                {
                    this._Currency = base.CreateQuery<global::ODataClientConsoleApplication.DataAccess.DataBase.Currency>("Currency");
                }
                return this._Currency;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::ODataClientConsoleApplication.DataAccess.DataBase.Currency> _Currency;
        /// <summary>
        /// There are no comments for Bank in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Bank")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::ODataClientConsoleApplication.DataAccess.DataBase.Bank> Bank
        {
            get
            {
                if ((this._Bank == null))
                {
                    this._Bank = base.CreateQuery<global::ODataClientConsoleApplication.DataAccess.DataBase.Bank>("Bank");
                }
                return this._Bank;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::ODataClientConsoleApplication.DataAccess.DataBase.Bank> _Bank;
        /// <summary>
        /// There are no comments for City in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("City")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::ODataClientConsoleApplication.DataAccess.DataBase.City> City
        {
            get
            {
                if ((this._City == null))
                {
                    this._City = base.CreateQuery<global::ODataClientConsoleApplication.DataAccess.DataBase.City>("City");
                }
                return this._City;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::ODataClientConsoleApplication.DataAccess.DataBase.City> _City;
        /// <summary>
        /// There are no comments for CurrencyRateByTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToCurrencyRateByTime(global::ODataClientConsoleApplication.DataAccess.DataBase.CurrencyRateByTime currencyRateByTime)
        {
            base.AddObject("CurrencyRateByTime", currencyRateByTime);
        }
        /// <summary>
        /// There are no comments for BankDepartment in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToBankDepartment(global::ODataClientConsoleApplication.DataAccess.DataBase.BankDepartment bankDepartment)
        {
            base.AddObject("BankDepartment", bankDepartment);
        }
        /// <summary>
        /// There are no comments for Currency in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToCurrency(global::ODataClientConsoleApplication.DataAccess.DataBase.Currency currency)
        {
            base.AddObject("Currency", currency);
        }
        /// <summary>
        /// There are no comments for Bank in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToBank(global::ODataClientConsoleApplication.DataAccess.DataBase.Bank bank)
        {
            base.AddObject("Bank", bank);
        }
        /// <summary>
        /// There are no comments for City in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToCity(global::ODataClientConsoleApplication.DataAccess.DataBase.City city)
        {
            base.AddObject("City", city);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""DataAccess.DataBase"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""CurrencyRateByTime"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""CurrencyId"" Type=""Edm.Int32"" />
        <Property Name=""BankDepartmentId"" Type=""Edm.Int32"" />
        <Property Name=""DateTime"" Type=""Edm.DateTimeOffset"" Nullable=""false"" />
        <Property Name=""Sale"" Type=""Edm.Double"" Nullable=""false"" />
        <Property Name=""Purchase"" Type=""Edm.Double"" Nullable=""false"" />
        <NavigationProperty Name=""BankDepartment"" Type=""DataAccess.DataBase.BankDepartment"">
          <ReferentialConstraint Property=""BankDepartmentId"" ReferencedProperty=""Id"" />
        </NavigationProperty>
        <NavigationProperty Name=""Currency"" Type=""DataAccess.DataBase.Currency"">
          <ReferentialConstraint Property=""CurrencyId"" ReferencedProperty=""Id"" />
        </NavigationProperty>
      </EntityType>
      <EntityType Name=""BankDepartment"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Name"" Type=""Edm.String"" />
        <Property Name=""Address"" Type=""Edm.String"" />
        <Property Name=""CityId"" Type=""Edm.Int32"" />
        <Property Name=""BankId"" Type=""Edm.Int32"" />
        <NavigationProperty Name=""Bank"" Type=""DataAccess.DataBase.Bank"">
          <ReferentialConstraint Property=""BankId"" ReferencedProperty=""Id"" />
        </NavigationProperty>
        <NavigationProperty Name=""City"" Type=""DataAccess.DataBase.City"">
          <ReferentialConstraint Property=""CityId"" ReferencedProperty=""Id"" />
        </NavigationProperty>
        <NavigationProperty Name=""CurrencyRateByTime"" Type=""Collection(DataAccess.DataBase.CurrencyRateByTime)"" />
      </EntityType>
      <EntityType Name=""Currency"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Name"" Type=""Edm.String"" />
        <NavigationProperty Name=""CurrencyRateByTime"" Type=""Collection(DataAccess.DataBase.CurrencyRateByTime)"" />
      </EntityType>
      <EntityType Name=""Bank"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Name"" Type=""Edm.String"" />
        <NavigationProperty Name=""BankDepartment"" Type=""Collection(DataAccess.DataBase.BankDepartment)"" />
      </EntityType>
      <EntityType Name=""City"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Name"" Type=""Edm.String"" />
        <NavigationProperty Name=""BankDepartment"" Type=""Collection(DataAccess.DataBase.BankDepartment)"" />
      </EntityType>
    </Schema>
    <Schema Namespace=""Default"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityContainer Name=""Container"">
        <EntitySet Name=""CurrencyRateByTime"" EntityType=""DataAccess.DataBase.CurrencyRateByTime"">
          <NavigationPropertyBinding Path=""BankDepartment"" Target=""BankDepartment"" />
          <NavigationPropertyBinding Path=""Currency"" Target=""Currency"" />
        </EntitySet>
        <EntitySet Name=""BankDepartment"" EntityType=""DataAccess.DataBase.BankDepartment"">
          <NavigationPropertyBinding Path=""Bank"" Target=""Bank"" />
          <NavigationPropertyBinding Path=""City"" Target=""City"" />
          <NavigationPropertyBinding Path=""CurrencyRateByTime"" Target=""CurrencyRateByTime"" />
        </EntitySet>
        <EntitySet Name=""Currency"" EntityType=""DataAccess.DataBase.Currency"">
          <NavigationPropertyBinding Path=""CurrencyRateByTime"" Target=""CurrencyRateByTime"" />
        </EntitySet>
        <EntitySet Name=""Bank"" EntityType=""DataAccess.DataBase.Bank"">
          <NavigationPropertyBinding Path=""BankDepartment"" Target=""BankDepartment"" />
        </EntitySet>
        <EntitySet Name=""City"" EntityType=""DataAccess.DataBase.City"">
          <NavigationPropertyBinding Path=""BankDepartment"" Target=""BankDepartment"" />
        </EntitySet>
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    return global::Microsoft.OData.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
}
